name: build

on:
  workflow_run:
    workflows: test
    # tags: v[\d.]+
    types: completed

env:
  PYCURL_SSL_LIBRARY: openssl
  PYLOAD_BUILD: ${{ github.run_number }}

jobs:
  sdist:
    name: Build source
    if: github.event.workflow_run.conclusion == 'success'

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip setuptools

      - name: Build pyLoad
        run: python setup.py -q sdist --formats=gztar,zip
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/*.{tar.gz,zip}

  bdist:
    name: Build binary
    if: github.event.workflow_run.conclusion == 'success'

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip setuptools wheel Babel Jinja2

      - name: Build pyLoad
        run: python setup.py -q build_locale bdist_wheel

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/*.whl
