name: No Response

on:
  issue_comment:
    types: [created]
  schedule:
    # Schedule for five minutes after the hour, every hour
    - cron: '5 * * * *'

jobs:
  noResponse:
    runs-on: ubuntu-latest
    steps:
      - uses: lee-dohm/no-response@v0.5.0
        with:
          token: ${{ github.token }}


# Number of days of inactivity before an Issue is closed for lack of response
daysUntilClose: 14

# Label requiring a response
responseRequiredLabel: "feedback wanted"

# Comment to post when closing an Issue for lack of response. Set to `false` to disable
closeComment: >
  **This ticket has been automatically closed**.


  This is because additional information has been requested,
  but no response has been given in the last **2 weeks**.

  Feel free to reopen this ticket if you need.


  Thanks for your contributions.
